const storageKey = "naming-decision-lab:v1";
const batchSize = 20;
const $ = id => document.getElementById(id);
const elements = {
  bridgeStatus: $("bridge-status"), activeDecisionTitle: $("active-decision-title"), decisionCount: $("decision-count"), decisionsToggle: $("decisions-toggle"), decisionDialog: $("decision-dialog"), closeDecisions: $("close-decisions"), decisionList: $("decision-list"), newDecisionForm: $("new-decision-form"), newDecisionTitle: $("new-decision-title"), newDecisionBrief: $("new-decision-brief"), createDecision: $("create-decision"), newDecisionMessage: $("new-decision-message"), decisionKind: $("decision-kind"), decisionHeading: $("decision-heading"), decisionBrief: $("decision-brief"), resultsCount: $("results-count"), batchNumber: $("batch-number"), progressText: $("progress-text"), progressBar: $("progress-bar"), undo: $("undo"), deck: $("deck"), card: $("card"), cardTerritory: $("card-territory"), cardName: $("card-name"), cardDescription: $("card-description"), cardSource: $("card-source"), batchComplete: $("batch-complete"), reflection: $("reflection"), dictate: $("dictate"), dictateLabel: $("dictate-label"), dictationMessage: $("dictation-message"), generate: $("generate"), continueSeed: $("continue-seed"), generating: $("generating"), generationMessage: $("generation-message"), analysis: $("analysis"), analysisText: $("analysis-text"), analysisTags: $("analysis-tags"), stats: $("stats"), historyList: $("history-list"), reset: $("reset")
};
const now = () => new Date().toISOString();
const newId = prefix => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function freshDecision(input = {}) {
  const isNaming = input.kind === "naming" || input.id === "chatbot-naming";
  const candidates = input.candidates || (isNaming ? [...window.SWIPE_SEED] : []);
  return { id: input.id || newId("decision"), title: input.title || "Untitled decision", brief: input.brief || "", kind: input.kind || "decision", createdAt: input.createdAt || now(), candidates, ratings: input.ratings || [], batches: input.batches || [], batch: input.batch || 1, activeIds: input.activeIds || candidates.slice(0, batchSize).map(item => item.id), nextSeed: input.nextSeed || (isNaming ? batchSize : candidates.length), latestAnalysis: input.latestAnalysis || null };
}
function freshWorkspace() { return { version: 2, activeId: "chatbot-naming", decisions: [freshDecision({ id: "chatbot-naming", title: "AI assistant naming", brief: "Find a clear, distinctive product name for a WordPress-first AI assistant for website visitors.", kind: "naming" })] }; }
function normalizeWorkspace(raw) {
  let workspace;
  if (raw?.version === 2 && Array.isArray(raw.decisions)) workspace = raw;
  else if (raw?.candidates?.length) workspace = { version: 2, activeId: "chatbot-naming", decisions: [freshDecision({ ...raw, id: "chatbot-naming", title: "AI assistant naming", brief: "Find a clear, distinctive product name for a WordPress-first AI assistant for website visitors.", kind: "naming" })] };
  else workspace = freshWorkspace();
  const imports = window.DECINDER_IMPORTS || [];
  imports.forEach(item => { if (!workspace.decisions.some(decision => decision.id === item.id)) workspace.decisions.push(freshDecision(item)); });
  if (!workspace.decisions.some(decision => decision.id === workspace.activeId)) workspace.activeId = workspace.decisions[0].id;
  return workspace;
}
function load() { try { return normalizeWorkspace(JSON.parse(localStorage.getItem(storageKey))); } catch { return normalizeWorkspace(null); } }
let workspace = load(); let state = activeDecision(); let bridgeAvailable = false; let drag = null; let isTransitioning = false; let recognition = null; let isDictating = false; let scoreFilter = null;
function activeDecision() { return workspace.decisions.find(item => item.id === workspace.activeId) || workspace.decisions[0]; }
function syncActive() { state = activeDecision(); scoreFilter = null; }
function bridgeHost() { return location.port === "4310"; }
function save() { localStorage.setItem(storageKey, JSON.stringify(workspace)); if (bridgeAvailable) fetch("/api/state", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ state: workspace }) }).catch(() => { bridgeAvailable = false; elements.bridgeStatus.textContent = "Bridge connection lost — saved in this browser"; }); }
function candidate(id) { return state.candidates.find(item => item.id === id); }
function currentBatchRatings() { const ids = new Set(state.activeIds); return state.ratings.filter(item => ids.has(item.id)); }
function currentCandidate() { const rated = new Set(currentBatchRatings().map(item => item.id)); return state.activeIds.map(candidate).find(item => item && !rated.has(item.id)); }
function scoreForPoint(x, y) { const rect = elements.deck.getBoundingClientRect(); const right = x > rect.left + rect.width / 2; const bottom = y > rect.top + rect.height / 2; return bottom ? (right ? 5 : 2) : (right ? 4 : 3); }
function decisionLabel() { return state.kind === "naming" ? "Naming direction" : "Decision"; }
function renderDecisionList() {
  elements.decisionCount.textContent = workspace.decisions.length;
  elements.decisionList.replaceChildren(...workspace.decisions.map(item => { const button = document.createElement("button"); button.type = "button"; button.className = item.id === state.id ? "is-active" : ""; const count = document.createElement("span"); count.textContent = `${item.ratings.length} rated`; const title = document.createElement("strong"); title.textContent = item.title; const brief = document.createElement("small"); brief.textContent = item.brief || "No brief added"; button.append(title, count, brief); button.addEventListener("click", () => { workspace.activeId = item.id; syncActive(); save(); render(); elements.decisionDialog.close(); }); return button; }));
}
function render() {
  const done = currentBatchRatings().length; const item = currentCandidate();
  elements.resultsCount.textContent = state.ratings.length;
  elements.activeDecisionTitle.firstChild.textContent = `${state.title} `;
  elements.decisionKind.textContent = `${decisionLabel()} · Batch ${String(state.batch).padStart(2, "0")}`;
  elements.decisionHeading.innerHTML = state.kind === "naming" ? "Rate the pull,<br />not just the name." : `Rate the pull on<br />${state.title}.`;
  elements.decisionBrief.textContent = state.brief || "Swipe diagonally, or use the score controls. Every completed 20-card batch can teach the next one.";
  elements.batchNumber.textContent = String(state.batch).padStart(2, "0"); elements.progressText.textContent = `${Math.min(done + 1, batchSize)} of ${batchSize}`; elements.progressBar.style.width = `${(done / batchSize) * 100}%`; elements.undo.disabled = state.ratings.length === 0;
  elements.batchComplete.hidden = done < batchSize; elements.deck.parentElement.hidden = done >= batchSize; elements.continueSeed.hidden = state.kind !== "naming";
  if (item) { elements.cardTerritory.textContent = item.territory; elements.cardName.textContent = item.name; elements.cardDescription.textContent = item.description; elements.cardSource.textContent = item.source === "seed" ? "Initial decision field" : "Generated for this decision"; elements.card.style.transform = "translate(0,0) rotate(0)"; }
  renderDecisionList(); renderHistory(); renderAnalysis();
}
function renderHistory() {
  const counts = [2,3,4,5].map(score => state.ratings.filter(item => item.score === score).length);
  elements.stats.replaceChildren(...counts.map((count, i) => { const score = i + 2; const tag = document.createElement("button"); tag.type = "button"; tag.className = scoreFilter === score ? "is-active" : ""; tag.setAttribute("aria-pressed", String(scoreFilter === score)); tag.textContent = `${score}: ${count}`; tag.addEventListener("click", () => { scoreFilter = scoreFilter === score ? null : score; renderHistory(); }); return tag; }));
  elements.historyList.replaceChildren(); [...state.ratings].reverse().filter(rating => scoreFilter === null || rating.score === scoreFilter).forEach(rating => { const item = candidate(rating.id); if (!item) return; const node = document.getElementById("history-row").content.cloneNode(true); node.querySelector(".history-score").textContent = rating.score; node.querySelector("h3").textContent = item.name; node.querySelector("p").textContent = item.description; node.querySelector("small").textContent = item.territory; const actions = node.querySelector(".history-actions"); [2,3,4,5].forEach(score => { const button = document.createElement("button"); button.type = "button"; button.className = rating.score === score ? "is-current" : ""; button.setAttribute("aria-label", `Change ${item.name} to score ${score}`); button.setAttribute("aria-pressed", String(rating.score === score)); button.textContent = score; button.addEventListener("click", () => changeScore(rating, score)); actions.appendChild(button); }); elements.historyList.appendChild(node); });
}
function renderAnalysis() { const data = state.latestAnalysis; elements.analysis.hidden = !data; if (!data) return; elements.analysisText.textContent = data.analysis; elements.analysisTags.replaceChildren(...[...(data.likes || []), ...(data.avoids || []).map(item => `Avoid: ${item}`)].map(text => { const tag = document.createElement("span"); tag.className = "tag"; tag.textContent = text; return tag; })); }
function scoreExit(score) { return ({ 2: [-34, 24, -8], 3: [-34, -24, -8], 4: [34, -24, 8], 5: [34, 24, 8] })[score]; }
function setScoreControls(disabled) { document.querySelectorAll("[data-score]").forEach(button => button.disabled = disabled); }
function rate(score) { const item = currentCandidate(); if (!item || isTransitioning) return; isTransitioning = true; setScoreControls(true); const [x, y, rotate] = scoreExit(score); elements.card.classList.add("is-leaving"); elements.card.style.transform = `translate(${x}vw,${y}vh) rotate(${rotate}deg)`; window.setTimeout(() => { state.ratings.push({ id: item.id, score, at: now(), batch: state.batch }); save(); render(); elements.card.classList.remove("is-leaving"); elements.card.classList.add("is-entering"); requestAnimationFrame(() => elements.card.classList.remove("is-entering")); isTransitioning = false; setScoreControls(false); }, 165); }
function changeScore(rating, score) { if (rating.score === score) return; const stored = state.ratings.find(item => item.id === rating.id && item.at === rating.at); if (!stored) return; stored.score = score; stored.changedAt = now(); save(); render(); }
function undo() { state.ratings.pop(); save(); render(); }
function nextSeedBatch() { const ids = state.candidates.filter(item => item.source === "seed").slice(state.nextSeed, state.nextSeed + batchSize).map(item => item.id); if (!ids.length) return generateMessage("This initial field is complete. Ask Codex for the next batch."); state.batches.push({ batch: state.batch, reflection: elements.reflection.value.trim(), source: "seed" }); state.batch += 1; state.activeIds = ids; state.nextSeed += ids.length; elements.reflection.value = ""; save(); render(); }
function generateMessage(message) { elements.generationMessage.textContent = message; }
async function checkBridge() { if (!bridgeHost()) { bridgeAvailable = false; elements.bridgeStatus.textContent = "Local generation is available at localhost"; return; } try { const [health, stored] = await Promise.all([fetch("/api/health", { cache: "no-store" }), fetch("/api/state", { cache: "no-store" })]); if (!health.ok || !stored.ok) throw new Error(); bridgeAvailable = true; const remote = await stored.json(); if (remote.state) { workspace = normalizeWorkspace(remote.state); syncActive(); save(); } else save(); elements.bridgeStatus.textContent = "Local Codex + shared SQLite ready"; } catch { bridgeAvailable = false; elements.bridgeStatus.textContent = "Bridge unavailable"; } }
async function generate() { if (!bridgeAvailable) return generateMessage("Open Decinder through the local bridge to generate the next batch."); stopDictation(); elements.generate.disabled = true; elements.continueSeed.disabled = true; elements.generating.hidden = false; elements.generate.textContent = "Analyzing…"; generateMessage("Codex is analyzing this batch and drafting 20 new cards…"); const ratings = state.ratings.map(rating => { const item = candidate(rating.id); return { name: item.name, territory: item.territory, description: item.description, score: rating.score, batch: rating.batch }; }); try { const response = await fetch("/api/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ratings, reflection: elements.reflection.value.trim(), count: 20, decision: { title: state.title, brief: state.brief } }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Generation failed"); const generated = result.names.map((item, index) => ({ id: `generated-${Date.now()}-${index}`, ...item, source: "generated" })); state.candidates.push(...generated); state.batches.push({ batch: state.batch, reflection: elements.reflection.value.trim(), source: "codex", analysis: result.analysis }); state.latestAnalysis = result; state.batch += 1; state.activeIds = generated.map(item => item.id); elements.reflection.value = ""; save(); render(); generateMessage("New 20-card batch is ready."); } catch (error) { generateMessage(error instanceof Error ? error.message : "Generation failed"); } finally { elements.generating.hidden = true; elements.generate.disabled = false; elements.continueSeed.disabled = false; elements.generate.textContent = "Analyze & generate 20"; } }
function speechRecognition() { return window.SpeechRecognition || window.webkitSpeechRecognition; }
function stopDictation() { if (recognition) recognition.stop(); }
function setupDictation() { const Recognition = speechRecognition(); if (!Recognition) { elements.dictate.disabled = true; elements.dictationMessage.textContent = "Dictation is not available in this browser. You can still type your reflection."; return; } elements.dictate.addEventListener("click", () => { if (isDictating) return stopDictation(); const initial = elements.reflection.value.trim(); let finalText = ""; let interimText = ""; recognition = new Recognition(); recognition.continuous = true; recognition.interimResults = true; recognition.lang = navigator.language || "en-US"; recognition.onstart = () => { isDictating = true; elements.dictate.setAttribute("aria-pressed", "true"); elements.dictateLabel.textContent = "Listening…"; elements.dictationMessage.textContent = "Listening. Tap again when you are done."; }; recognition.onresult = event => { for (let i = event.resultIndex; i < event.results.length; i += 1) { const text = event.results[i][0].transcript.trim(); if (event.results[i].isFinal) finalText += `${finalText ? " " : ""}${text}`; else interimText = text; } elements.reflection.value = [initial, finalText, interimText].filter(Boolean).join(initial && (finalText || interimText) ? " " : ""); }; recognition.onerror = event => { elements.dictationMessage.textContent = event.error === "not-allowed" ? "Microphone permission was not granted." : "Dictation stopped. You can type instead."; }; recognition.onend = () => { isDictating = false; elements.dictate.setAttribute("aria-pressed", "false"); elements.dictateLabel.textContent = "Dictate"; recognition = null; }; recognition.start(); }); }
async function createDecision(event) { event.preventDefault(); if (!bridgeAvailable) { elements.newDecisionMessage.textContent = "Open Decinder through the local bridge to create a separate decision."; return; } const title = elements.newDecisionTitle.value.trim(); const brief = elements.newDecisionBrief.value.trim(); if (!title || !brief) return; elements.createDecision.disabled = true; elements.createDecision.textContent = "Creating cards…"; elements.newDecisionMessage.textContent = "Codex is preparing a distinct first batch of 20 cards."; try { const response = await fetch("/api/decisions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, brief, count: 20 }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not create decision"); workspace = normalizeWorkspace(result.workspace); workspace.activeId = result.decision.id; syncActive(); localStorage.setItem(storageKey, JSON.stringify(workspace)); elements.newDecisionForm.reset(); render(); elements.decisionDialog.close(); } catch (error) { elements.newDecisionMessage.textContent = error instanceof Error ? error.message : "Could not create decision"; } finally { elements.createDecision.disabled = false; elements.createDecision.textContent = "Create 20 cards"; } }
document.querySelectorAll("[data-score]").forEach(button => button.addEventListener("click", () => rate(Number(button.dataset.score)))); elements.undo.addEventListener("click", undo); elements.continueSeed.addEventListener("click", nextSeedBatch); elements.generate.addEventListener("click", generate); elements.decisionsToggle.addEventListener("click", () => elements.decisionDialog.showModal()); elements.closeDecisions.addEventListener("click", () => elements.decisionDialog.close()); elements.newDecisionForm.addEventListener("submit", createDecision); elements.reset.addEventListener("click", () => { if (confirm(`Clear ratings for ${state.title}?`)) { state.ratings = []; state.batches = []; state.batch = 1; state.activeIds = state.candidates.slice(0, batchSize).map(item => item.id); state.nextSeed = state.kind === "naming" ? batchSize : state.candidates.length; state.latestAnalysis = null; save(); render(); } });
elements.card.addEventListener("pointerdown", event => { if (isTransitioning) return; drag = { x: event.clientX, y: event.clientY }; elements.card.setPointerCapture(event.pointerId); }); elements.card.addEventListener("pointermove", event => { if (!drag || isTransitioning) return; const dx = event.clientX - drag.x, dy = event.clientY - drag.y; elements.card.style.transform = `translate(${dx}px,${dy}px) rotate(${dx / 22}deg)`; }); elements.card.addEventListener("pointerup", event => { if (!drag || isTransitioning) return; const dx = event.clientX - drag.x, dy = event.clientY - drag.y; drag = null; if (Math.hypot(dx, dy) < 55) return render(); rate(scoreForPoint(event.clientX, event.clientY)); }); window.addEventListener("keydown", event => { if (["2", "3", "4", "5"].includes(event.key) && !elements.batchComplete.hidden) return; if (["2", "3", "4", "5"].includes(event.key)) rate(Number(event.key)); if (event.key.toLowerCase() === "z" && (event.metaKey || event.ctrlKey)) undo(); });
setupDictation(); checkBridge().finally(() => { syncActive(); render(); });
